### ISSUE TITLE
Error when using API's built-in delete handler

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#103]
Code:
```js
{ route: '/:_id?', handlers: [ 'get', 'post', 'put', 'delete' ] }
```
Record is successfully deleted from database but responds with
```console
TypeError: Cannot read property 'length' of undefined
    at App.instance.getModule.then.data (D:\adapt-authoring\node_modules\adapt-authoring-api\lib\utils.js:27:19)
```

**Comment by taylortom** [comment]
Can't replicate this one

**Comment by tomgreenfield** [comment]
Current error:
```console
(node:6068) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at D:\adapt-authoring\node_modules\adapt-authoring-api\lib\abstractApiModule.js:24:34
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
