### ISSUE TITLE
MongoDB module typos

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#127]
https://github.com/adapt-security/adapt-authoring-mongodb/blob/ec3ea1f4bae61cd74f0284ebebd668ef5e5377dd/lib/module.js#L15

```console
Error: Failed to delete document(s), Cannot read property 'lang' of undefined
    at MongoDBModule.formatError (D:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\module.js:223:15)
    at D:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\module.js:188:21
    at new Promise (<anonymous>)
    at MongoDBModule.delete (D:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\module.js:183:12)
    at D:\adapt-authoring\node_modules\adapt-authoring-api\lib\utils.js:44:20
    at new Promise (<anonymous>)
    at Function.callDbFunction (D:\adapt-authoring\node_modules\adapt-authoring-api\lib\utils.js:29:12)
    at D:\adapt-authoring\node_modules\adapt-authoring-api\lib\module.js:23:16
    at uninstallPlugin (D:\adapt-authoring\node_modules\adapt-authoring-contentplugin\lib\abstractContentPluginApiModule.js:61:52)
```
---
https://github.com/adapt-security/adapt-authoring-mongodb/blob/ec3ea1f4bae61cd74f0284ebebd668ef5e5377dd/lib/module.js#L190

```console
Uncaught TypeError: Cannot read property 'filter' of undefined
    at eval (eval at <anonymous> (D:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\module.js:190:7), <anonymous>:1:16)
    at D:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\module.js:190:7
    at new Promise (<anonymous>)
    at MongoDBModule.delete (D:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\module.js:183:12)
    at D:\adapt-authoring\node_modules\adapt-authoring-api\lib\utils.js:44:20
    at new Promise (<anonymous>)
    at Function.callDbFunction (D:\adapt-authoring\node_modules\adapt-authoring-api\lib\utils.js:29:12)
    at D:\adapt-authoring\node_modules\adapt-authoring-api\lib\module.js:23:16
    at uninstallPlugin (D:\adapt-authoring\node_modules\adapt-authoring-contentplugin\lib\abstractContentPluginApiModule.js:61:52)
```

**Comment by taylortom** [comment]
Can't replicate, will need to check this one again

**Comment by taylortom** [comment]
Have fixed the first issue, can't replicate the second any more. Please retest.

**Comment by tomgreenfield** [comment]
Can't replicate these at present.
