### ISSUE TITLE
Error: Failed to create new document d is not defined

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#199]
On a `mongodb.insert()`:
```console
error server Error: Failed to create new document d is not defined
    at MongoDBModule.formatError (F:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\mongoDBModule.js:182:15)
    at MongoDBModule.insert (F:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\mongoDBModule.js:106:18)
```

**Comment by tomgreenfield** [comment]
If this has been fixed, maybe sort the error handling so we see a better stack.

**Comment by tomgreenfield** [comment]
New error:
```console
error server Error: Failed to create new document Cannot create property '_id' on string 'extensions'
    at MongoDBModule.formatError (F:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\mongoDBModule.js:182:15)
    at MongoDBModule.insert (F:\adapt-authoring\node_modules\adapt-authoring-mongodb\lib\mongoDBModule.js:106:18)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by taylortom** [comment]
This one should be fixed
