### ISSUE TITLE
Investigate contentplugin module boot error

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#253]
```
2020-07-31T10:31:50.680Z error DependencyLoader Failed to load module 'adapt-authoring-contentplugin'
2020-07-31T10:31:50.680Z error DependencyLoader TypeError: Cannot read property 'commands' of undefined
    at Object.<anonymous> (node_modules/adapt-authoring-contentplugin/lib/contentPluginModule.js:2:37)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (node_modules/adapt-authoring-contentplugin/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at DependencyLoader.loadModule (node_modules/adapt-authoring-core/lib/dependencyloader.js:102:20)
    at node_modules/adapt-authoring-core/lib/dependencyloader.js:134:20
```

**Comment by tomgreenfield** [comment]
Resolved for now; leaving open to update dependency once adapt-cli has been released.

**Comment by tomgreenfield** [comment]
Fixed.
