### ISSUE TITLE
ContentPluginModule error on installPlugins

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring#337]
The adapt-cli seems to cause an error which is undefined in a catch statement...
```
2020-11-26T20:17:26.499Z error contentplugin TypeError: Cannot read property 'code' of undefined
    at ContentPluginModule.installPlugins (/home/tom/Projects/adapt/adapt-authoring/node_modules/adapt-authoring-contentplugin/lib/ContentPluginModule.js:81:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

```

**Comment by taylortom** [comment]
Can't replicate this now the new schemas have been sorted
