### ISSUE TITLE
Startup fails due to missing 'inquirer' dependency

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#355]
One to keep an eye on:
```console
2021-01-26T15:43:20.268Z error DependencyLoader Failed to load 'adapt-authoring-contentplugin', Error: Cannot find module 'inquirer'
Require stack:
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/create.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/index.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/cli.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-contentplugin/lib/ContentPluginModule.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-contentplugin/index.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-core/lib/DependencyLoader.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-core/lib/App.js
- /opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-core/index.js
- /opt/adapt/testing.kineoadapt.com/bin/start.js
- /opt/adapt/testing.kineoadapt.com/bin/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/create.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at /opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/index.js:8:19
    at Array.reduce (<anonymous>)
    at Object.<anonymous> (/opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/index.js:6:45)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/create.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/commands/index.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-cli/lib/cli.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-contentplugin/lib/ContentPluginModule.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-contentplugin/index.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-core/lib/DependencyLoader.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-core/lib/App.js',
    '/opt/adapt/testing.kineoadapt.com/node_modules/adapt-authoring-core/index.js',
    '/opt/adapt/testing.kineoadapt.com/bin/start.js',
    '/opt/adapt/testing.kineoadapt.com/bin/cli.js'
  ]
}
```

**Comment by tomgreenfield** [comment]
I haven't seen this recently, touch wood.
