### ISSUE TITLE
'collection already exists' error on startup

### ISSUE THREAD

**Issue by tomgreenfield** [adapt-security/adapt-authoring#357]
```console
LoggerModule.js:148 2021-01-26T17:12:41.579Z error mongodblogger MongoError: collection already exists
    at MessageStream.messageHandler (F:\adapt-authoring\node_modules\mongodb\lib\cmap\connection.js:268:20)
    at MessageStream.emit (events.js:315:20)
    at processIncomingData (F:\adapt-authoring\node_modules\mongodb\lib\cmap\message_stream.js:144:12)
    at MessageStream._write (F:\adapt-authoring\node_modules\mongodb\lib\cmap\message_stream.js:42:5)
    at writeOrBuffer (_stream_writable.js:352:12)
    at MessageStream.Writable.write (_stream_writable.js:303:10)
    at Socket.ondata (_stream_readable.js:719:22)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
    at TCP.callbackTrampoline (internal/async_hooks.js:129:14)
```

**Comment by tomgreenfield** [comment]
Suggest `e.code === 48` instead of [`e.codeName`](https://github.com/adapt-security/adapt-authoring-mongodblogger/blob/23098da10efb7699b10969194794d879f6b8a250/lib/MongoDBLoggerModule.js#L41).
