### ISSUE TITLE
Cannot upload an asset file on a clean install of the AT - adapt-authoring-assets

### ISSUE THREAD

**Issue by deltanetdan** [adapt-security/adapt-authoring#421]
On a clean install of the AT the following error gets returned when uploading an asset through the asset manager:

```
2021-07-28T15:01:16.658Z error server TypeError: fs.copy is not a function
    at AssetsRepository.save (/AAT-test/adapt-authoring/node_modules/adapt-authoring-assets/lib/assetsrepository.js:33:14)
    at Assetsmodule.importImage (/AAT-test/adapt-authoring/node_modules/adapt-authoring-assets/lib/importimages.js:6:48)
    at /AAT-test/adapt-authoring/node_modules/adapt-authoring-assets/lib/importimages.js:21:71
    at Array.map (<anonymous>)
    at Assetsmodule.importImages (/AAT-test/adapt-authoring/node_modules/adapt-authoring-assets/lib/importimages.js:21:50)
    at Layer.handle [as handle_request] (/AAT-test/adapt-authoring/node_modules/express/lib/router/layer.js:95:5)
    at next (/AAT-test/adapt-authoring/node_modules/express/lib/router/route.js:137:13)
    at Assetsmodule.importZips (/AAT-test/adapt-authoring/node_modules/adapt-authoring-assets/lib/importzips.js:76:12)
    at Layer.handle [as handle_request] (/AAT-test/adapt-authoring/node_modules/express/lib/router/layer.js:95:5)
    at next (/AAT-test/adapt-authoring/node_modules/express/lib/router/route.js:137:13)
```

Should [line 33](https://github.com/adapt-security/adapt-authoring-assets/blob/master/lib/assetsrepository.js#L33) be:
`await fs.copyFile(file, dest);`

**Comment by fkcailiniyazi** [comment]
Hello Dan,

just updated that line.
