### ISSUE TITLE
Configmodule.js LOAD_ERROR

### ISSUE THREAD

**Issue by KristofferBroberg** [adapt-security/adapt-authoring#619]
### What happened?

Attempting clean install of RC 3

Error 500 LOAD_ERROR when installer tries to fetch configmodule.js.

Also tried running cmd as administrator thinking it had something to do with folder privilegies.

Windows 10, prereqs are met.

### Steps to reproduce

Run a clean install on my computer :)

### Authoring tool version

rc3

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Relevant log output

```sh
Installing npm dependencies
adapt-authoring-server: /url must match format "uri",
Error
    at ConfigModule.storeSchemaSettings (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-config/lib/ConfigModule.js:135:27)
    at async ConfigModule.init (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-config/lib/ConfigModule.js:36:7)

Config failed to initialise for environment 'production'. See above for details.

Failed to load 'adapt-authoring-config', AdaptError: LOAD_ERROR
    at Object.get [as LOAD_ERROR] (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-errors/lib/ErrorsModule.js:53:20)
    at ConfigModule.init (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-config/lib/ConfigModule.js:42:29) {
  code: 'LOAD_ERROR',
  statusCode: 500,
  meta: { description: 'Config failed to load' }
}
Failed to load 'adapt-authoring-mongodb', AdaptError: LOAD_ERROR
    at Object.get [as LOAD_ERROR] (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-errors/lib/ErrorsModule.js:53:20)
    at ConfigModule.init (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-config/lib/ConfigModule.js:42:29) {
  code: 'LOAD_ERROR',
  statusCode: 500,
  meta: { description: 'Config failed to load' }
}
The following modules are peer dependencies, and may not work:
- adapt-authoring-api
- adapt-authoring-tags
- adapt-authoring-ratelimiter
- adapt-authoring-courseassets
Failed to load 'adapt-authoring-logger', AdaptError: LOAD_ERROR
    at Object.get [as LOAD_ERROR] (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-errors/lib/ErrorsModule.js:53:20)
    at ConfigModule.init (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-config/lib/ConfigModule.js:42:29) {
  code: 'LOAD_ERROR',
  statusCode: 500,
  meta: { description: 'Config failed to load' }
}
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

AdaptError: LOAD_ERROR
    at Object.get [as LOAD_ERROR] (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-errors/lib/ErrorsModule.js:53:20)
    at ConfigModule.init (file:///C:/Users/kristoffer.broberg/adapt/node_modules/adapt-authoring-config/lib/ConfigModule.js:42:29) {
  code: 'LOAD_ERROR',
  statusCode: 500,
  meta: { description: 'Config failed to load' }
}

Node.js v18.14.2
```

**Comment by KristofferBroberg** [comment]
duplicate of at-utils #22
